/* **************************\
Component: Global Constants
Explanation:
Global constants to be shared all over the app

\*************************** */


export default {
    common: {
        cancel: "Cancel",
        ok: "Okay",
        enable: "Enable",
        back: "Back",
        submit: "Submit",
        done: "Done",
        error: "Error",
        close: "Close",
        save: "Save",
        accept: "Accept",
        edit: "Edit",
        upgrade: "Upgrade",
        languageCode: "en",
        settings: "Settings",
        open: "Open",
        discard: 'Discard',
        closed: "Closed",
        closes: "Closes",
        no: 'No',
        yes: "Yes",
        downloadPDF: "Download PDF",
        next: "Next",
        more: "more",
        remove: "Remove",
        update: "Update",
        agree: "Agree",
        browse: "Browse",
        select: "Select",
        continue: "Continue",
        delete: "Delete",
        connectWithUs: "Connect with Us",
        privacyPolicy: "Privacy Policy",
        fundDocuments: "Fund Documents",
        userAgreement: "User Agreement",
        support: "Support",
        copyRights: "Copyright Victory Capital Management Inc. ©2020",
        validPincode: "Enter Valid 6 Digit Pin",
        dollar:"$",
        validate:"Validate",
        upload:"Upload"
    },
    login: {
        imageRequest: "imageRequest",
        FACE_ID: 'FaceID',
        TOUCH_ID: 'TouchID',
        SUCCESS: "success"
    },
    maxLength: {
        nickname: 50,
        firstName: 40,
        middleInitial: 40,
        lastName: 40,
        prefix: 10,
        suffix: 10,
        gender: 1,
        dob: 10,
        martialStatus: 10,
        emailID: 30,
        ssnNo: 9,
        company:30,


        address: 60,
        addressLine1: 50,
        addressLine2: 50,
        houseNo: 50,
        streetName: 50,
        streetNo: 50,
        zipCode: 5,
        city: 30,
        state: 30,
        foreignPostalcode: 8,
        country: 30,

        workPhone: 10,
        phoneNo: 10,
        mobileNo: 10,

        occupation: 30,
        employerName: 40,
        emplAddress1: 60,
        emplAddress2: 60,
        primarySourceIncome: 50,
        industry: 30,

        seniorPoliticalMaxLength: 50,
        usaaNo: 11,
        vcmNo: 11,
        relationship: 30,
        name: 80,
        distributionPercentage: 3,

        initInvestment: 10,
        monthlyInvestment: 10,
        accountNumber:15,
        transitRoutingNumber:9,
        common:250,


    },
    dashBoard: {
        openAnAccount: "Open an Account",
        dashboard: "DASHBOARD",
        openAnAccountWithVCM: "Open an account with Victory Capital",

        termsAndConditions: "Terms and Conditions",
        termsAndConditionsNote: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
        basicTerms: "Basic Terms",
        agreeMsgContent: "By checking this box, I acknowledge that I have read the preceding terms and condition and that I understand, assent to, and agree to comply with, those terms and conditions"

    },
    accManagement: {
        // labels 
        accType: "Account Type",
        generalInvestmentAcc: "General Investment Account",
        retirementAcc: "Retirement Accounts",
        investingChildrenAcc: "Investing for Children",
        specialtyAcc: "Specialty Accounts",

        personalize: "Personalize",
        nickname: "Nick Name",
        optional: "(Optional)",
        uploadImage: "Upload Image",
        uploadW8Form: "Upload W-8 form",
        whatISW8Form:"What is W-8 form?",

        //manage beneficiearies
        manageBeneficiaries: "Manage Beneficiaries",
        contactUs: "Contact Us",
        myAccountBeneficiariesInfo: "My Accounts / Beneficiary Information",
        beneficiariesAccount: "The following contracts / accounts are available for you to view and update your beneficiaries. If your contracts / beneficiaries are not shown here please ",
        traditionalIra: "Traditional IRA",
        contractNumber: "Contract Number",
        primaryBeneficiary: "Primary Beneficiary",
        rothIra: "Roth IRA",
        accumulatedValue:"Accumulated Value",
        contingentBeneficiary: "Contingent Beneficiary",
        dob: "Date of Birth",
        beneficiary_type:"Beneficiary Type",
        registrationOwner:"Registration Owner",
        relationToOwner: "Relationship to Account owner",
        relationToInsured:"Relationship to Insured",
        distribution: "Distribution",
        accBeneficiaryContent: "You may name one or more people or entities as beneficiaries. Learn more",
        beneficiaryAdd:"Beneficiary Address",
        company:"Company",
        editPrimaryBene:"Edit Primary Beneficiary Information",
        editContingentBene:"Edit Contingent Beneficiary Information",
        editTodBene:"Edit Transfer on Beneficiary Information",
        verifyTOD:"Verify-Transfer on Death Beneficiary Information",
        addPrimaryBeneficiary:"Add Primary Beneficiary",
        contingentInfo:"Contingent Beneficiary Information",
        primaryInfo:"Primary Beneficiary Information",
        balance:"Balance",
        zipCodeFormat:"11111 / 11111-1111",
        beneficiaryName:"Beneficiary Name",
        enterDetailsPrimaryDisc:"Distributions for primary beneficiary and for contingent beneficiary must equal 100 percentage.",
        enterDetailsContingentBene:"Contingent beneficiary are recommended but not required.",
        enterDetailsIfYouWish:"If you wish to select a spouse or child and that person is not listed, you may add them in your Profile Page If your request cannot be completed using the selections below, please Contact Us.",
        enterDetailsIfNoBene:"If no beneficiary designation has been received and accepted by the custodian prior to your account (Account Owner) death, or if all of your designated beneficiaries have predeceased you, then your beneficiary sahll be your surviving spouse or, if there is no surviving spouse, then the account owner's estate. See the custodial agreement and disclosure statement applicable to your Victory Capital retirement plan for complete information.",
        enterDetailsAdditionalAdvisor:"Additionally, you should contact your legal advisor regarding your specific situation.",
        pleaseProvideCorrectAdd:"Please provide full address. If you do not know the address, please remove and submit without address",
        emptyDistributionMsg:"Please Enter Distribution %",
        distributionValidationExceed:"Distribution should not exceed 100",
        firstNameFormat:"Please Enter Valid First Name",
        lastNameFormat:"Please Enter Valid Last Name",
        addContingentBeneficiary:"Add Contingent Beneficiary",
        emptyBeneficiaryType:"Please Select Beneficiary Type",

        //manageIntrestedParties
        manageIntrestedParties: "Manage Interested Parties",
        listOfIntrestedParties: "List of Interested Parties",
        addNew: "Add New",
        addNewIntrestedParties: "Add New Interested Party",
        statements: "Statements",
        prospectusAndReports: "Prospectus and Reports",
        selectDocumentType:"Select Document Type",
        selectDocumentFrequency:"Select Document Frequency",
        intrestedPartiesAddedSuccessMeg:"Interested Party Added Successfully",
        selectDocuemntDeleveryFormat:"Select Document Delivery Format",   
        emptyDocumentFrequencyMsg:"Select the DocumentFrequency",
        validateRelation:"Please Select the relation",


        personalInformation: "Personal Information",
        employmentInformation: "Employment Information",
        financialInformation: "Financial Information",
        militaryInformation: "Military Information",
        regulatoryQuestion: "Regulatory Question",
        regulatoryNoteTxt: "This Question is required by financial regulatory agencies",
        regulatoryQuestTxt: "Are you a senior foreign political figure, a family member or associate of a senior foreign political figure?",
        personalInformationJoint: "Personal Information - Joint Owner",
        employmentInformationJoint: "Employment Information - Joint Owner",
        financialInformationJoint: "Financial Information - Joint Owner",
        militaryInformationJoint: "Military Information - Joint Owner",
        regulatoryQuestionJoint: "Regulatory Question - Joint Owner",

        personalInformationChild: "Personal Information - Child Beneficiaries",
        regulatoryQuestionChild: "Regulatory Question - Child Beneficiaries",

        childBeneficiaryNote: "Note : Different states have different definitions and ways to determine a child's minor status.",

        VCPrivacyNotice: "Victory Capital Privacy Notice",
        VCPrivacyNoticeDesc: "Victory Capital encrypts sensitive information to ensure it remains confidential",
        VCDiscalimerTitle: "Investing involves risk including loss of principal.",
        VCDiscalimerDesc: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Captial Advisers,Inc.(VCA).VictoryShares ETFs and VictoryShares USAA ETFs.",
        VCDiscalimerDescContent: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license.",
        beneficiariesOpt: "Beneficiaries (optional)",
        beneficiariesNote: "You may name one or more people or entities as beneficiaries",
        beneficiariesCond: "Primary distributions must total 100 percent",


        suffix: "Suffix",
        prefix: "Prefix",
        firstName: "First Name",
        middleInitial: "Middle Initial",
        lastName: "Last Name",
        suffixOptional: "Suffix (Optional)",
        maritalStatus: "Marital Status",
        gender: "Gender",
        usaaNo: "USAA Number (optional)",
        vcmNo: "VCM Number",

        dob: "Date of Birth",
        addressType: "Address Type",
        mailingAddressType: "Mailing Address Type",

        isYourPhysicalAddressSame: "Is your physical address same as mailing address ?",
        mobileNo: "Mobile Number",
        telePhoneNo2: "Phone Number 2",
        contactMeDuring: "Call Time Preference",
        telePhoneNo3: "Phone Number 3",




        mailingAddress: "Mailing Address",
        physicalAddress: "Physical Address",
        address: "Address",
        phoneType: "Phone Type",
        phoneNo: "Phone Number",
        phoneNoFormat: "XXX-XXX-XXXX",
        emailAddress: "Email Address",
        socialSecurityNo: "Social Security Number",
        ssnNoFormat: "XXX-XXX-XXXX",
        citizenship: "Citizenship",

        empStatus: "Employment Status",
        industry: "Industry",
        occupation: "Occupation",
        name: "Name",
        empName: "Employer's Name",
        empAddress: "Employer's Address",
        empAddrLine1: "Line 1",
        empAddrLine2: "Line 2",
        workPhoneNo: "Work Telephone",
        zipcode: "ZIP Code",
        cityAndState: "City & State",
        city: "City",
        state: "State",
        seniorPoliticalName: "Senior Foreign Political Figure Name",

        annualIncome: "Annual Income (USD)",
        taxBracket: "Tax Bracket  (Percentage)",
        networth: "Net Worth (USD)",
        taxFilingStatus: "Tax Filing Status",
        servingStatus: "Are you currently serving, or have you ever served in the US Military?",
        militaryStatus: "Military Status",
        branchOfService: "Branch of Service",
        rank: "Rank",
        datesOfService: "Dates of Service",
        from: "From",
        to: "To",
        commissionSource: "Commission Source",


        homeTelephone: "Home Telephone",
        relationshipCustodian: "Relationship to Custodian",
        relationshipToAccHolder: "Relationship to Account Holder",

        relationship: "Relationship",

        beneficiary: "Beneficiary",
        distributionPercentage: "Distribution Percentage",
        ssnTINno: "Social Security Number/ TIN",
        explainTin: "Expalin TIN",
        addAnotherBeneficiary: "+ Add another Primary Beneficiary (Up to 3)",

        investmentSelection: "Investment Selection",
        selectYourMutualFunds: "Select your VCM Mutual Funds",
        investmentSelectionNote: "Select up to 10 funds from the list below. Use the filter to narrow the list",
        fundYourAccount: "Fund Your Account",
        fundYourAccountNote: "Choose how you will fund your account and indicate your initial investment amount.",
        fundYourInvest: "Fund Your Investments",
        fundYourInvestNote: "Choose your funding options below. For monthly investments, the start day of the month must be a business day and at least 1 business day from today. If the day of the month you select is a holiday, the transaction will occur on the next business day. If you are selecting a monthly investment, please read this important notice",

        fundName: "Fund Name",
        fundingOptions: "Funding Options",
        initInvestment: "Initial Investment",
        monthlyInvestment: "Monthly Investment",
        startDate: "Start Date",
        total: "Total",
        filterFunds: "Filter Funds",
        compareFunds: "Compare Funds (up to 4)",
        minimum: "Minimum",
        minWithAutoInvesting: "Min w/ Auto Investing",
        risk: "Risk",
        minW: "Min w/",
        autoInvetsing: "Auto Investing",
        minimumInvestment:"Minimum Investment",
        fundType:"Fund Type",
        clearFilter:"Clear Filters",
        applyFilter:"Apply Filter",
        contactMSR:"Contact MSR",
        callTollFee:"Call toll-free",
        callTollFeeNo:"(855) 756-7520",

        contactMSRDesc:"Lorem ipsum dolor sit amet, consectetur adipiscing elitdh Nam imperdiet dictum orcittet",
        offlineMethod: "Offline Method",
        offlineMethodDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elitdh Nam imperdiet dictum orcittet",
        onlineMethod: "Online Method",
        onlineMethodDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elitdh Nam imperdiet dictum orcittet",

        addBankAccount: "Add Bank Account",
        typeOfAccount: "Type of Account",
        savings: "Savings",
        checking: "Checking",
        financialInstitution: "Name of Financial Institution",
        accountOwner: "Name of Accouner Owner(s)",
        transitRoutingNo: "Transit Routing Number",
        accountNumber: "Account Number",
        specimen: "SPECIMEN",
        accNumberOwnerDesc:"Account number and all owner names must be preprinted and unaltered",

        backtInvestmentSelection: "Back to Investment Selection",
        summary: "Summary",
        quickFacts: "Quick Facts",
        performance: "Performance",
        monthEndAvgAnnualReturns: "Month-End Average Annual Total Returns as of ",
        quarterEndAvgAnnualReturns: "Quarter -End Average Annual Total Returns as of ",

        YTD: "YTD",
        oneYear: "1 Year",
        fiveYear: "5 Year",
        tenYear: "10 Year",
        sinceInception: "Since Inception",
        netAssetValue: "Net Asset Value",
        pricePerShare: "(price per share as of ",
        expenseRation: "Expense Ratio",
        overallMrngStarRating: "Overall Morningstar Rating",
        mrngStarCategory: "Morningstar Category",
        fundsInCategory: "Funds in Category",
        riskLevel: "Risk Level",
        riskSummary: "The Fund's investment objective is capital appreciation. The fund invests primarily in equity securities of large capitalization companies that are selected for their growth potential. Although the fund will invest primarily in U.S. securities, it may invest upto 20% of its total assets in foreign securities including securities issued in emerging markets.",
        investmentMinimums: "Investment Minimums",
        initMonthlyInvestment: "Initial and Monthly Investment",
        moreInfo: "More Information",
        fullFundDeatilDisclosures: "Full Fund Detail and Important Disclosures",





        preferences: "Preferences",
        genealAccPreferences: "General Account Preferences",
        genealAccPreferencesNote: "You can change your preferences on usaa.com or by calling a representative",
        dividensAndCapitalQuest: "What do you want to do with your dividends/ capital gains?",
        explainDividensAndCapitalGains: "Explain Dividends/Capital Gains",
        dividensAndCapitalGains: "Dividends/Capital Gains",
        reinvestDividensAndCapitalGains: "Reinvest dividends and capital gains of all eligible securities",
        reinvestDividensAndCapitalGainsNote: "Example: If your fund pays a dividend, the proceeds will be used to purchase more shares of that fund",
        transferDividensAndCapitalGains: "Electronically transfer dividends and capital gains to your bank",
        transferDividensAndCapitalGainsNote: "Example: If your fund pays a dividend, the proceeds will be used to purchase more shares of that fund",
        prospectusReports: "Statements Prospectus and Reports",
        desiredFormatDelivaryDocs: "Desired format for delivery of documents",
        explainprospectusReports: "Explain Prospectus & Reports Preference",
        sendProspectusReportsCopy: "Send only one copy of prospectuses and reports to my household",
        selectProspectusReportsCopy: "Select copies of prospectuses and reports to each individual investor in my household",

        vcmInvestAccInfo: "VCM Investment Account Information",
        registrationType: "Registration Type",
        personalInfoPrimary: "Personal Information - Primary",
        employmentInfoPrimary: "Employment Information - Primary",

        verifyInfo: "Verify",
        selectedMutualFunds: "Selected Mutual Funds",
        fundingInfo: "Funding Information",
        fundingSource: "Funding Source",
        totalInitInvestment: "Total Initial Investment",
        accountFeatures: "Account Features",
        prospectus: "Prospectus",

        eSign: "E-Sign",
        TINBackupCert: "Taxpayer Identification Number/ Backup withholding certification",
        IRSNotify: "The Internal Revenue Service (IRS) has not notified me that I am subject to backup withholding",
        IRSUnNotify: "The IRS has notified me that I am subject to backup withholding as a result of:",
        UnNotifyAspectOne: "I reported an incorrect Social number to the IRS with my tax filling.",
        UnNotifyAspectTwoM: "I failed to report all interest and dividends on previous year's tax returns.",
        docToView: "Documents to View",
        docToSign: "Documents to Sign",
        docToSignNote: "You'll need the free Adobe Reader to view these documents.",
        agreeConditions: "I, Agree that I have received, read, understood, and agree to the documents linked below.",
        IRSConsentMsg: "The Internal Revenue Service does not require your consent to any provision of this document other than the certifications required to avoid backup withholding.",

        ESA: "ESA",
        ElectronicSErviceAgreement: "(Electronic Services Agreement)",
        ESADescription: "You must complete the Electronic Services Agreement before you will be able to complete any financial transactions in your Investment account(s) on vcm.com or on the VCM Self-Service Telephone System.",
        ESADescImportant: "IMPORTANT: Read the document below, print and save it for your records. It includes legally required disclosures/information. It will not be mailed to you.",
        ESANote: "You must read, scroll and click the button to agree to the document below.",
        VCMElectronicService: "VCM Electronic Service Agreement",
        VCMElectronicServiceDesc: "The VCM Investment Management Company (IMCO) Electronic Services Agreement allows you to complete financial transactions, obtain real-time quotes and other information in your investment accounts.",
        saveDocument: "Save Document",
        printVersion: "Print Version",
        signThisDocument: "Sign this Document",
        ESATermsCond: "By clicking “ I Agree,” I acknowledge that I am making this agreement in my individual capacity solely for my person, non-business use and that I agree to the terms and conditions of the VCM Electronic Service Agreement. This is my electronic signature.",

        ApplicationPart1: "Application - Part 1",
        ApplicationPart2: "Application - Part 2",

        personalAndBeneficiaryInfo: "(Personal & Beneficiary Info)",
        chooseYourPortfolio: "(Choose your Portfolio)",
        howLongItWillTake: "How long will it take?",
        about5to10minutes: "About 5 to 10 minutes.",
        whatYouWillNeed: "What you will need:",
        whatYouWillNeedNote: "Ensure all information under your Personal Profile is current . The Social Security number of the person you are opening an account for. Ensure the Citizenship of the person you are opening an account for, is entered in your VCM Personal Profile.",
        whatToExpect: "What to expect?",
        whatToExpectNote: "For Part 2, you'll be sent to secure website built exclusively for VCM members to choose your portfolio options.",
        ApplicationPart1Note: "Note: f you are interested in establishing Trust as the account owner, you can apply via email or VCM investment professional at 002928825 Monday-Friday, 7:30.m-8p.m CT. and Sm.-5p.m CT n Saturday",
        ApplicationPartDisclaimer: "Consider the investment objectives, risks, charges and expenses of the VCM 529 College Savings Plan (Plan) carefully before investing. Download a Plan Description and Participation Agreement (PDF) containing this and other information about the Plan from VCM Investment Management Company, Underwriter and Distributor, Read it carefully before investing. If you or the beneficiary are not residents of the state of Nevada, consider before investing whether your or the designated beneficiary's home state offers any state tax or other state benefits such as financial aid, scholarship funds, and protection from creditors that are only available for investments in such state's qualified tuition program Please consult your tax advisor.",
        getStarted: "Get Started",

        whyWeNeedThis: "Why we need this?",

        beneficiaryInfo: "Beneficiary Information",
        planBeneficiary: "Plan Beneficiary",
        chooseThePersonWhoseEducation: "Choose the person whose college education you are saving for.",
        whoWillBeTheBeneficiary: "Who will be the beneficiary of this plan?",
        successorAccOwnerInfo: "Successor Account Owner Information",
        successorAccOwnerInfoQuest: "Do you want to name someone who can become the owner or successor of the account if you become unable to continue?",





        // placeholder
        enterName: "Enter Name",
        enterZip: "Enter Zip",
        enterCity: "Enter City",
        selectCity: "Select City",
        enterState: "Enter State",
        selectState: "Select State",
        enterSeniorName: "Enter Senior Foreign Political Figure Name",
        emailformat: "youremail@VCM.com",




        // Err messages
        emptyAccType: "Please select an account",
        emptyRegTypeMsg: "Please select any Registraion Type",


        emptyNickNameMsg: "Please enter Nickname of your account",
        emptyPrefixMsg: "Please select Prefix of your name",
        emptyFirstNameMsg: "Please enter First name",
        emptyLastNameMsg: "Please enter Last name",
        emptyDOBMsg: "Please enter valid Date of Birth",
        emptyGenderMsg: "Please select Gender",
        emptyMaritalMsg: "Please select Marital Status",
        emptyCitizenshipMsg: "Please select Citizenship ",
        emptyMailingAddressTypeMsg: "Please select Address Type",
        emptyAddressTypeMsg: "Please select Address Type",
        emptyAddressLine1Msg: "Please enter Address Line 1",
        emptyAddressLine2Msg: "Please enter Address Line 2",
        emptyMailingAddressMsg: "Please enter Mailing Address",
        emptyPhysicalAddressMsg: "Please enter Physical address",
        emptyZipCodeMsg: "Zip code is required",
        invalidZipCodeMsg: "Invalid Zip code",
        emptyCityMsg: "Please enter City",
        emptyStateMsg: "Please select State",
        emptyCountry: "Please select a country",
        confirmPhysicalAddressSame: "Please indicate if the physical address is same as mailing address",
        emptyMobileNoMsg: "Mobile Number is required",
        invalidMobileNoMsg: "Invalid Mobile Number",
        emptyPhonenoMsg: "Home Telephone is required",
        invalidPhoneNoMsg: "Invalid Home Telephone",

        emptyEmailAddressMsg: "Email Address is required",
        invalidEmailMasg: "Your Email Address is not valid.Please enater a valid email eddress",
        emptySSNMsg: "Please enter SSN",
        invalidSSNMsg: "SSN is invalid",
        emptyVCMNoMsg: "Please enter VCM Number",
        invalidVCMNoMsg: "VCM Number is invalid",

        emptyEmploymentStatusMsg: "Please Select Employment Status",
        emptyOccupationMsg: "Please enter Occupation",
        emptyEmployerNameMsg: "Please enter Employer's Name",
        emptyEmployerAddressLine1Msg: "Please enter Employer Address Line 1",
        emptyEmployerAddressLine2Msg: "Please enter Employer Address Line 2",
        emptyWorkPhoneNoMsg: "Work Telephone is required’",
        invalidWorkPhoneNoMsg: "Invalid Work Telephone",


        emptyIsSeniorPoliticalFigureMsg: "Please indicate whether you are a senior foreign political figure or not.",
        emptySeniorPoliticalNameMsg: "Please enter Senior Foreign Political Figure Name",
        emptyRelationTypeMsg: "Please select a relationship to custodian",
        emptySeletedFundMsg: "Atleast one fund should be selected",
        maximumSeletedFundMsg: "Maximm 10 funds only allowed",
        emptyFundingSourceMsg: "Atleast one funding source should be selected",
        emptyFundOptionsMsg: "Please select a funding options",
        emptyInitInvestmentMsg: "Please enter a initial investment value",
        minInitInvestmentMsg: " Initial investment value should me minimum of $ 3000",
       
        emptyTypeOfAccount: "Please select type of account ",
        emptyFinancialInstitution: "Enter Valid Financial Institution",
        emptyAccountOwnerName: "Enter Valid Owner Name",
        emptyTransitRoutingNo: "Enter Valid Transit Routing Number",
        emptyAccountNumber: "Enter Valid Account Number",

        invalidInitInvestmentMsg: "‘Please enter a valid initial investment  value",
        emptyMonthlyInvestmentMsg: "‘Please enter a monthly investment value",
        minMonthlyInvestmentMsg: " Monthly investment value should me minimum of $ 3000",

        invalidMonthlyInvestmentMsg: "‘Please enter a valid monthly investment value",
        emptyStartDate: "Please select a start date",
        emptyDividendCapitalGainsMsg: "Please select any type of Dividend/Capital Gains",
        emptyProspectusReportsRefMsg: "Please select any type of Prospectus & Reports reference",
        confirmTINBackupWithholdingMsg: "Please conirm TIN / Backup Holding Certification",
        confirmAgreeCondMsg: "Please agree terms & conditions",
        confirmBeneficiaryforThePlanMsg: "Please confirm Who will be the beneficiary of this plan?",
        emptyRelationShipMsg: "Please select Relationship",
        emptySuccessOwnerMsg: "Please select Success Owner Infomation",
        emptymilitaryServingStatus: "Please indicate whether you are currently serving, or have you ever served in the US Military?",






    },
    userManagement: {
        changeLogonCredentials: "Change Sign In Credentials",
        changeLogonSelection: "Select from below options to change your Logon credentials",
        resetPassword: "RESET PASSWORD",
        selectToChangePswd: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        lastUpdate: "Last update : 21 May 2018 1:22 PM",
        resetPIN: "RESET PIN",
        pinLengthLessThanFour: 'PIN length is less than 4 digits',
        selectToChangePIN: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        back: "Back",
        VCDiscalimerTitle: "Investing involves risk including loss of principal.",
        VCDiscalimerDesc: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license.",
        VCPrivacyNoticeDesc: "Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license.",
        accountRecPrefHeading: "Account Recovery Preferences",
        accountRecPrefSelection: "Set your account recovery preference from the below options",
        emailId: "Email id ",
        emailIdSelection: "Your registered email will be your account recovery option",
        textMessageTo: "Text Message to ",
        mobileNoSelection: "Your registered mobile no will be your account recovery option",
        cancel: "Cancel",
        save: "Save",
        restYourPIN: "Reset PIN",
        restYourPassword: "Reset Password",
        enterCurrentPIN: "Enter Current PIN",
        enterCurrentPassword: "Enter Current Password",
        enterNewPIN: "Enter New PIN",
        enterNewPassword: "Enter New Password",
        confirmNewPIN: "Confirm New PIN",
        confirmNewPassword: "Confirm New Password",
        changePIN: "Change PIN",
        submit: "Submit",
        pinDoesntMatch: "Both PIN do not match",
        passwordDoesnotMatch: "Both passwords do not match",
        currentPIN: "Current PIN",
        currentPassword: "Current Password",
        newPIN: "New PIN",
        newPassword: "New Password",
        explain: "Explain",
        strong: "Strong",
        good: "Good",
        weak: "Weak",
        changedPasswordSuccessfully: "Your Password has been successfully changed.",
        changedPINSuccessfully: "Your PIN has been successfully changed.",
        accRecPrefEmailText: "Your Account Recovery Preferences is set to Email and Text Message",
        accRecPrefText: "Your Account Recovery Preferences is set to Text Message",
        accRecPrefEmail: "Your Account Recovery Preferences is set to Email",
        pleaseEnterCurrentPswd:"Please enter current password",
        enteredIncorrectPswd:"Entered incorrect password",
        pleaseEnterCurrentPIN:"Please enter current PIN",
        enteredIncorrectPIN:"Entered incorrect PIN",
        modifySecurityHeading: "Modify Security Questions",
        modifySecuritySelect: "Select and Answer to three Security Questions",
        changeSignInHeading: "Change SignIn Method",
        changeSignInHeadingSoftToken: "Change SignIn Method to SoftToken",
        changeSignInHeadingOTP: "Change SignIn Method to OneTime Password",
        changeSignInHeadingPushNotification: "Change SignIn Method to Push Notification",
        changeSignInSelection: "Select from Below Option to Change your Logon Method",
        quickSigninEnabledText: "You have enabled Quick SignIn in you vcm App",
        toEnable: "To enable again use your vcm mobile App",
        toDisable: "Choose to disable it",
        otp: "Your Sign Method has Successfully Changed to OTP",
        pushNotification: "Your Sign Method has Successfully Changed to Push Notification",
        softToken: "Your Sign Method has Successfully Changed to Soft Token",
        downloadTokengen: "Download token generation application from below link and enter token details",
        downloadPushNotification: "Download the app which can generate Push Notification ",
        saveCurrentDevice: "Save Current Device",
        checkTheOption: "Check this option to save current device and skip OTP authentication",
        otpSignon: "Select from Below Options to set your preferred Sign On method",
        firstToken: "First Token",
        secondToken: "Second Token",
        additionaProtection: "Additional Protection",
        ques1: "Question1",
        ques2: "Question2",
        ques3: "Question3",
        confirmPEmail: "Confirm Primary Email",
        documentDeliveryPreference: "Update Document Delivery Preference",
        addAdditionalEmail: "Add Additional Email",
        profilePreferences: "Profile",
        profile: "Basic Information",
        deliverySettings: "Delivery Setting",
        accouintMessaging: "Account Messaging",
        securityPreferences: "Security",
        marketingPrivacy: "Marketing & Privacy",
        securityPref: "Security Preferences",
        changeSigninCredentials: "CHANGE SIGN IN CREDENTIALS",
        setAccountRecoveryPreferences: "SET ACCOUNT RECOVERY PREFERENCES",
        modifySecurityQuestions: "MODIFY SECURITY QUESTIONS",
        chooseSigninMethods: "CHOOSE SIGN IN METHODS",
        welcomeTextProfile: "Welcome <User Name> to Victory Capital. You have successfully logged as <Online ID>. Set up your Security Preferences Now",
        managePersonalDetails: "Manage your personal details",
        mobileQuickSignIn: "MOBILE QUICK SIGN IN",
        dropDownError: "Questions Are Same Please Select Different Question",
        inputError: "Please Enter your Answer",
        emailError: "Please Enter Valid Email",
        loremSecurityPref: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        securityText:"For security reasons, not all information can be updated online. Please call us if you need assistance with link to VCM support number <Phone Number>",
        manageDeliverySettings: "Manage your delivery settings",
        manageAccountMessaging: "Manage your account messaging",
        manageSecurityDetails: "Manage your security details",
        manageMarketingDetails: "Manage your marketing & privacy details",
    },

    settingAccountMessaging: {
        setting: "Setting",
        settingArrow: "Setting    >",
        accountMessagingTitle: "Account Messaging",
        accountMessagingArrow: ">    Account Messaging",
        accountMessagingTitleDesc: "Lorem Ipsum is dummy text of the typesetting industry.",

        // Title and Title Descriptions Settings > Account Messaging
        goalTitle: "Goals",
        goalTitleDesc: "Lorem Ipsum has been the industrys standard dummy text ever since the 1500s",
        adviceTitle: "Advice",
        adviceTitleDesc: "Lorem Ipsum has been the industrys standard dummy text ever since the 1500s",
        generalDocumentsTitle: "General Documents",
        generalDocumentsTitleDesc: "Lorem Ipsum has been the industrys standard dummy text ever since the 1500s",
        securityAndFraudAlertsTitle: "Security And Fraud Alerts",
        securityAndFraudAlertsTitleDesc: "Lorem Ipsum has been the industrys standard dummy text ever since the 1500s",
        deviceManagementTitle: "Device Management",
        deviceManagementTitleDesc: "Lorem Ipsum has been the industrys standard dummy text ever since the 1500s",

        // Title and Title Descriptions Settings > Account Messaging > Goals
        accountMessagingGoalsArrow: ">    Goals",
        accountMessagingGoalTitleDesc: "Lorem Ipsum is dummy text of the typesetting industry.",
        accountMessagingGoalDebtManagementGoal: "Debt Management Goal",
        accountMessagingGoalAlertForGoals: "Alerts for Goals",
        accountMessagingGoalNoGoals: "Currently there are only alerts for Debt Goals",
        accountMessagingGoalCreateGoal: "Create a Goal",

        // Title and Title Descriptions Settings > Account Messaging > Advice
        accountMessagingAdviceArrow: ">     Advice",
        accountMessagingAdviceTitleDesc: "Lorem Ipsum is dummy text of the typesetting industry.",
        accountMessagingAdviceSwitchOn: "On",
        accountMessagingAdviceSwitchOff: "Off",

        accountMessagingAdviceRetirement: "Retirement",
        accountMessagingAdviceGettingStarted: "Getting Started in Retirement",
        accountMessagingAdviceLivingRetirement: "Living Retirement",
        accountMessagingAdviceGrowingRetirement: "Growing Your Retirement",
        accountMessagingAdviceEastPlanning: "East Planning",

        accountMessagingAdvicePersonalFinance: "Personal Finance",
        accountMessagingAdviceTaxCenter: "Tax Center",
        accountMessagingAdviceUnderstandInvest: "Understanding Investments",
        accountMessagingAdviceSavingBudget: "Saving and Budgeting",
        accountMessagingAdviceDebtCredit: "Debt and Credit",
        accountMessagingAdviceFinancialSet: "Financial Setbacks",

        accountMessagingAdviceFamilyLife: "Family Life",
        accountMessagingAdviceGettingMarried: "Getting Married",
        accountMessagingAdviceBecomingParent: "Becoming a Parent",
        accountMessagingAdviceParenting: "Parenting",
        accountMessagingAdviceYoungAdults: "For Young Adults",
        accountMessagingAdviceGettingDivorce: "Getting a Divorce",
        accountMessagingAdviceLossLovedOne: "Loss of a Loved One",
        accountMessagingAdviceLifeInsurance: "Life Insurance",
        accountMessagingAdviceHealthInsurance: "Health Insurance",

        accountMessagingAdviceMilitaryLife: "Military Life",
        accountMessagingAdviceJoinMilitary: "Joining the Military",
        accountMessagingAdviceDeployment: "Deployment",
        accountMessagingAdvicePcs: "PCS",
        accountMessagingAdviceLeavingMilitary: "Leaving the Military",

        // Title and Title Descriptions Settings > Account Messaging > General Documents
        accountMessagingGeneralArrow: ">     General Documents",
        accountMessagingGeneralTitleDesc: "Lorem Ipsum is dummy text of the typesetting industry.",
        accountMessagingGeneralAlertForDocument: "Alerts for All Documents",
        accountMessagingGeneralAlertNoAlerts: "There are no alerts available for Documents",
        accountMessagingGeneralTaxDocuments: "Tax Documents",
        accountMessagingGeneralHowLike: "How would you like to receive documents for all tax accounts?",
        accountMessagingGeneralWouldLike: "Would you like all of your other documents from VCM Delivered the same way?",
        accountMessagingGeneralHowLikeGeneral: "How would you like to receive documents for all general accounts?",
        accountMessagingGeneralAnnualReport: "Annual Reports",
        accountMessagingGeneralPrivacyPromise: "Privacy Promise",
        accountMessagingGeneralSomeDoc: "Some documents any not be immediately available in large Print, Braille and/or Screen Reader formats Have questions? View our ",
        accountMessagingGeneralFaqPage: "FAQ page",
        accountMessagingGeneralAdditionalAssist: " for additional assistance.",
        accountMessagingGeneralStillReceive: "You will still get paper documents if other account holders have selected that option. For credit accounts, monthly statements will not be mailed if any account holder has selected online.",

        accountMessagingGeneralOnline: "Online",
        accountMessagingGeneralPaper: "Paper",
        accountMessagingGeneralLargePrint: "Large Print & Paper",
        accountMessagingGeneralBraillePaper: "Braille & Paper",
        accountMessagingGeneralScreenReader: "Screen Reader Compatible & Online",

        // Title and Title Descriptions Settings > Account Messaging > Alerts for Security and Fraud
        accountMessagingSecurityFraudArrow: ">     Alerts for Security and Fraud",
        accountMessagingSecurityFraudTitle: "Alerts for Security and Fraud",
        accountMessagingSecurityFraudTitleDesc: "Lorem Ipsum is dummy text of the typesetting industry.",
        accountMessagingSecurityFraudSuspicious: "If suspicious activity occurs on your account, you will receive an alert. Responding to it as soon as possible helps us prevent financial loss and minimize any impact on you.",
        accountMessagingSecurityFraudLearnMore: "Learn more about how we safeguard your accounts and what you can do to help at our ",
        accountMessagingSecurityFraudCenter: "Security Center",
        accountMessagingSecurityFraudOnVcm: " on VCM.com",

        // Title and Title Descriptions Settings > Account Messaging > Device Management
        accountMessagingDeviceManageArrow: ">     Device Management",
        accountMessagingDeviceManageTitleDesc: "Lorem Ipsum is dummy text of the typesetting industry.",
        accountMessagingDeviceManagePushNotify: "Push notifications are automatically set up on the device you are using every time you access the VCM mobile app.",
        accountMessagingDeviceManageDeviceRemove: "Select the Devices you wish to remove."
    },

    settingsDeliveryPreference: {
        deliveryPreferenceTitle: "Delivery Settings",
        deliveryPreferenceTitleDesc: "Lorem Ipsum is dummy text of the typesetting industry.",
        deliveryPreferencearrow: ">    My Profile and preference",
        deliveryPreferenceNotifiedBy: "Get Notified By :",

        deliveryPreferenceEmail: "Email",
        deliveryPreferenceUrgentMessage: "Urgent Messages",
        deliveryPreferenceUrgentNotifications: "Notifications",
        deliveryPreferenceUrgentGuidanceGoals: "Guidance and Goals",
        deliveryPreferenceReadMore: "Read more...",
        deliveryPreferenceReadMoreUrgent: "Notify me of overdue bills, security issues, specified account activity, claims-related tasks and any other messages that I have set up as urgent.",
        deliveryPreferenceReadMoreNotification: "Notify me of new documents, application status changes, saved quotes and any other messages I have set up.",
        deliveryPreferenceReadMoreGuidance: "Notify me of guidance and action items based on my account activity, goals, checklists and any other messages that I have set up.",
        deliveryPreferencePushNotification: "Push Notification",
        deliveryPreferenceTextMessage: "Text Message",
        deliveryPreferenceCall: "Call Preference",
        deliveryPreferenceAvailability: "What is your preferred availability? ",
        deliveryPreferenceAvailabilityDesc: "optional This selection will apply to all of the phone numbers listed on your profile.",
        deliveryPreferenceAvailabilityDescPref: "if a preferred time to call you is not selected, we will continue to call you during VCM business hours and as permitted by law.",
        deliveryPreferenceQuietTime: "Quiet Time",
        deliveryPreferenceQuietTimeDelay: "You can delay text messages when using Quiet Time. To enable this feature, navigate to \"Delivery Settings\" in your VCM Mobile App.",
        priorityTextContent: "During the plot phase, certain limited alerts and notification related to specific programs and products will take priority above the preferences set in inbox.",
        priorityTextContentMessage: "Message categorization is provided as a tool but should not be relied on to determine which message need to be reviewed. All messages provided in inbox should be reviewed.",
        priorityTextContentText: "Text message frequency depends on your service selections. To cancel text message services at any time text",
        priorityTextContentStop: " STOP",
        priorityTextContentHelp: " HELP",
        priorityTextContentTo: " to",
        priorityTextContentMobileDevice: " from your mobile device. For more information, text",
        priorityTextContentMyVcm: " My VCM ",
        priorityTextContentDataRate: ". Message and Data Rates May Apply.",
        priorityTextContentVcm: "For VCM text messaging support call ",
        priorityTextContentSupport: "Support mobile carriers include AT&T, Sprint, T-Mobile, U.S. Cellular, Verizon Wireless - and more. View the entire list of ",
        priorityTextContentSupportMobile: "Supported Mobile Carriers",

        modalTitle: "Text Messaging Registration",
        modalRegisterText: "We just sent you a text message with your registration code to ",
        modalRegisterCodeText: "Enter Registration Code",
        modalDidntReceive: "Didn't receive a registration code within 10 minutes? ",
        modalResendCode: "Resend Code",
        modalEnterCorrectCode: "Enter the Correct Code",
        modalCodeSentSuccess: "Code has been sent successfully",
    },
    addFinancialInformations: {
        addFinancialTitle: "Manage Financial Information",
        annualIncome: "Annual Income (USD)",
        taxBracket: "Tax Bracket (Percentage)",
        netWorth: "Net Worth (USD)",
        taxFillingStatus: "Tax Filing Status",
        financialSecurity: "This information is collected on behalf of each of the VCM companies, and will be used for business purpose, including identification, verification of eligibility, and to market their products and services",
        financialInvesting: "Investing involves risk including loss of principal.",
        financialOpenInvestment: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license."
    },
    addPhoneNumber: {
        addPhoneTitle: "Add Number",
        phoneType: "Phone type",
        phoneNumber: "Phone Number",
        callTimePreference: "Call Time Preference",
        setPreferred: "Set Preferred",
        phoneSecurity: "For security reasons, not all information can be uploaded online. Please call us if you need assistance. Phone Number",
        phoneInvesting: "Investing involves risk including loss of principal.",
        phoneInvestments: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license."
    },
    addAddressInfo: {
        addAddressTitle: "Edit Contact Information",
        editAddressInformation: "Edit Contact Information",
        mailingAddress: "Mailing Address",
        addressType: "Address Type",
        radioButtonOne: "U.S. or U.S. Territories",
        radioButtonTwo: "APO (Army or Air Force Post Office)",
        radioButtonThree: "FPO (Fleet Post Office)",
        radioButtonFour: "DPO (Diplomatic Post Office)",
        addressLineOne: "Address Line 1",
        addressLineTwo: "Address Line 2",
        zipCode: "ZIP Code",
        cityLabel: "City",
        stateLabel: "State/Territory",
        addressTerms: "Investing involves risk including loss of principal.",
        addressInvestment: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license."
    },
    editAddressInfo: {
        editAddressTitle: "Manage Contact Information",
        editAddressInformations: "Manage Contact Information",
        editAddressAddNew: "Add",
        editAddressSetMailing: "Set as Mailing Address",
        editAddressSetPhysical: "Set as Physical Address",
        editAddressSecurity: "For security reasons, not all information can be uploaded online. Please call us if you need assistance. Phone Number",
        editAddressTerms: "Investing involves risk including loss of principal.",
        editAddressInvestments: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license."
    },
    editEmailInformations: {
        editEmailTitle: "Edit Email Information",
        editEmailAddNew: "Add New",
        editEmailPrimary: "Primary",
        editEmailSecondary: "Secondary",
        editEmailDelete: "Delete",
        editEmailPreferred: "Set Preferred",
        editEmailInfoOne: "You must have at least once email address on file",
        editEmailInfoTwo: "When You delete an email address. you'll no longer receive notifications or alert to the email.",
        editEmailSecurity: "For security reasons, not all information can be uploaded online. Please call us if you need assistance. Phone Number",
        editEmailTerms: "Investing involves risk including loss of principal.",
        editEmailInvestment: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license."
    },
    editMilitaryInfo: {
        militaryInfoTitle: "Manage Military Information",
        militaryServing: "Are you currently serving, or have you ever served in the US Military?",
        militaryInformations: "Please Provide current military information. We want to ensure that our members receive ourmost competitive offers and rates and are addressed according to correct military protocol"
    },
    editOccupationInfo: {
        occupationTitle: "Manage Occupation Information",
        occupationLabel: "Occupation",
        occupationEmployerName: "Employer Name",
        occupationEmployerOne: "Employer Line 1",
        occupationEmployerTwo: "Employer Line 2",
        occupationZipcode: "ZIP Code",
        occupationCity: "City",
        occupationState: "State/Territory",
        occupationOptional: "Optional",
        occupationHint: "This information is collected on behalf of each of the VCM companies, and will be used for business purpose, including identification, verification of eligibility, and to market their products and services",
        occupationIndustry: "Industry",
        occupationPrimarySource: "Primary Source of Income",
        occupationEmployment: "Employment Class",
        occupationIndustryChoose: "If you can't find an exact match for your industry or occupation, choose the closest one"
    },
    editPhoneInformations: {
        phoneInfoTitle: "Personal Profile Phone",
        phoneLabel: "Manage Phone Information",
        phoneAddNew: "Add",
        phoneMobileLabel: "Mobile",
        phonePrimaryNumber: "Primary Number",
        phonePreferred: "Preferred",
        phoneEditLabel: "Edit",
        phoneInvestment: "Victory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license.",
        phoneTerms: "Investing involves risk including loss of principal.",
        phoneSecurity: "For security reasons, not all information can be uploaded online. Please call us if you need assistance. Phone Number",
        phoneFaxLabel: "Fax Number",
        phoneFax: "Fax"
    }, recoverPassword: {
        validPassword: 'Enter valid password',
        guestTempPasswordNotify: 'A Temporary Password has been sent to your registered Email id ',
        guestTempPasswordTitle: 'Enter Temporary Password',
        guestTempPasswordLabel: 'Temporary Password',
        passwordPlaceHolder: '*******',
        err_onlineId: 'Enter a valid online Id',
        err_ssn: 'Enter a valid SSN',
        title_onlineId: 'Retrieve your\nPassword',
        lable_onlineId: 'Online ID',
        lable_ssn: 'Social Security Number(SSN)',
        placeholder_ssn: "23456",
        security: 'Security Check',
        refresh_security: 'Refresh Security check',
        lable_security: 'Security Check',
        enter_security: 'Enter Text above',
        err_security: 'Security code does not match',
        password_mismatch: "Password does not match",
        password_new_title: 'Create New Password',
        password_current: 'Enter current Password',
        password_new: 'Enter new Password',
        password_confirm: 'Confirm New Password',
        password_hint: 'Hint',
        btnChangePassword: "Change Password",
        otp_err: 'Enter valid otp',
        otp_notify: 'You have logged on to an unknown device. Enter OTP to proceed.',
        otp_label: 'Enter OTP',
        otp_textMsg: 'We have sent OTP to your registered Mobile no ',
        otp_reset: 'Resend OTP',
        password_suceess_head: 'Password Reset successful',
        password_success_title: 'Your password reset was successful.',
        password_success_msg1: 'You will now be redirected to Sign In Page',
        password_success_msg2: 'Need assistance ?  GetHelp',
        retrive_password: 'Enter below details to retrieve your Password',
        password_success_footer1: 'Neque porro quisquam est qui dolorem',
        password_success_footer2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet dictum orci et faucibus. Suspendisse non malesuada enim. Aliquam fringilla lectus ut massa convallis gravida. Integer condimentum mollis velit, nec porta diam mattis sit amet. Quisque sodales, enim quis laoreet aliquet, mauris nisi condimentum libero, a viverra ligula libero sed sem. Pellentesque sed mollis tortor, vitae finibus metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus blandit consequat arcu nec iaculis. Aenean at pharetra nisl. Sed eget turpis sit amet'
    },
    //Automatic Investment Plan
    automaticInvestment: {
        autoInves_Title: 'Automatic Investment Plan',
        autoInves_current: 'Current Automatic Investment Plans',
        autoInves_current_content: 'There are two parts for an automatic investment within an IRA. The first is the contribution to the account and sencond is the purchase of the mutual fund(s). if you\'re making a change, be sure adjust both parts',
        acc_Name: 'Account Name',
        skip: 'Skip',
    },
    profileSettingsPage: {
        profileDummyValue: " ",
        profileHeadOne: "Profile",
        profileHeadArrow: " > ",
        profileHeadTwo: "Basic Information",
        profilePersonalInfo: "Personal Information",
        profileManage: "Manage",
        profileNameLabel: "Name",
        profileRelationLabel: "Relationship",
        profilePrimaryLabel: "Primary",
        profileRelationInfoLabel: "Relationship Information",
        profileNameContentMsg: "If you need to change your name, please call us at <Phone Number>. Depending on the product and services you currently have, documentation may be required in order to make your update",
        profilePrefixLabel: "Prefix",
        profileSuffixLabel: "Suffix",
        profileVcmLabel: "VCM ID",
        profileSsnLabel: "Social Security Number",
        profileDobLabel: "Date of birth",
        profileGenderLabel: "Gender",
        profileStatusLabel: "Marital Status",
        profileCitizenLabel: "Citizenship",
        profileCountryLabel: "Country",
        profileCountryOfCitizen: "Country of Citizenship",
        profileCitizenProof: "Proof of Citizenship or Residency",
        profileUSCitizenLabel: "US Citizen",
        profileContactLabel: "Contact Information",
        profileMailingLabel: "Mailing Address",
        profilePhysicalLabel: "Physical Address",
        profilePhoneInfoLabel: "Phone Information",
        profilePrimaryMobileLabel: "Primary Mobile",
        profileMailLabel: "Email Information",
        profileMailPrimaryLabel: "Primary",
        profileFinancialInfo: "Financial Information",
        profileFinancialOne: "Annual Income",
        profileFinancialTwo: "Tax Bracket",
        profileFinancialThree: "Net Worth",
        profileFinancialFour: "Tax Filing Status",
        profileEmployeeInfo: "Employment Information",
        profileEmployeeOne: "Employment Status",
        profileEmployeeTwo: "Primary Industry",
        profileEmployeeThree: "Primary Occupation",
        profileEmployeeFour: "Primary Employer",
        profileMilitaryInfo: "Military information (Optional)",
        profileMilitaryProvideInfo: "Providing your current military information",
        profileRegulatoryInfo: "Regulatory questions",
        profileRegulatoryQues: "You are not a senior foreign political figure",
        profileRelationshipLabel: "Manage relationship",
        profileRelationshipAdd: "Add",
        profileFamilyMemberLabel: "Family Member Name",
        profileSocialMediaLabel: "Social Media Information",
        profileFacebookLabel: "Sign in to Facebook",
        profileTwitterLabel: "Sign in to Twitter",
        profileInvest: "Investing involves risk including loss of principal.\n\nVictory Mutual Funds and USAA Mutual Funds are distributed by Victory Capital Advisers, Inc. (VCA). VictoryShares ETFs and VictoryShares USAA ETFs are distributed by Foreside Fund Services, LLC (Foreside). VCA and Foreside are members of FINRA and SIPC. Victory Capital Management Inc. (VCM) is the investment adviser to the Victory Mutual Funds, USAA Mutual Funds, VictoryShares ETFs and VictoryShares USAA ETFs. VCA and VCM are not affiliated with Foreside. USAA is not affiliated with Foreside, VCM, or VCA. USAA and the USAA logos are registered trademarks and the USAA Mutual Funds and USAA Investments logos are trademarks of United Services Automobile Association and are being used by Victory Capital and its affiliates under license. Victory Capital means Victory Capital Management Inc., the investment manager of the USAA 529 College Savings Plan (Plan). The Plan is distributed by Victory Capital Advisers, Inc., a broker dealer registered with FINRA and an affiliate of Victory Capital. Victory Capital and its affiliates are not affiliated with United Services Automobile Association or its affiliates. USAA and the USAA logo are registered trademarks and the USAA 529 College Savings Plan logo is a trademark of United Services Automobile Association and are being used by Victory Capital and its affiliates under license.",
        profileSecurity: "For security reasons, not all information can be uploaded online. Please call us if you need assistance. Phone Number",
        profileSharing: "By Sharing and connecting your social media information with VCM., our team can streamline your experience on VCM's social presences such as Twitter and Facebook, and provide you with personalized tips, tools and support. All social media information collected by VCM is used and protected according to the VCM Private Promise and Online Information Practices"
    },
    editProfilePageValue: {
        editProfileManage: "Manage Personal Information",
        editProfileChosenLabel: "You have chosen to update your personal information on record with VCM.",
        editProfilePin: "Pin",
        editProfileInvesting: "Investing involves risk including loss of principal.",
        editAddressInfoHead: "Settings > Personal info > ",
        editManageRegulatory: "Manage Regulatory questions",
        editRegulatoryPoliticalLabel: "Are you are a senior foreign political figure ?"
    },
    editRelationShipInformation: {
        relationShipHeadLabel: "Manage Relationship Information",
        relationShipFamilyLabel: "Family Member's relationship to you",
        relationFirstName: "First Name",
        relationPrefix: "Prefix",
        relationSuffix: "Suffix",
        relationDob: "Date of Birth",
        relationGender: "Gender",
        relationStatus: "Marital Status",
        relationSocialSecurity: "Social Security number",
        relationInst: "Instructions",
        relationInstOne: "Please provide the details to add your family member.",
        relationInstTwo: "Select Next and we will search our records for a possible match.",
        relationInstThree: "If a match is not found, continue to provide information to add your family member to your personal profile",
        relationInstContent: "To help the government fight the funding of terrorism and money laundering activities, federal law requires all financai institutions to obtain, verify and record information that identifies each person who open an account. what this means for you: when open an account, we will ask for your name, address, date of birth and other information that will allow us to identify you. We may also ask to see your driver's license or other identifying documents."
    },
    profileValidationMessages: {
        validateAddressLineOne: "Enter a valid Address.",
        validateZipcode: "Enter a valid zipcode",
        validatePrefix: "Select Valid Prefix",
        validateSuffix: "Select Valid Suffix",
        validateGender: "Select Valid Gender",
        validateStatus: "Select Valid Marital Status",
        validateFinancialInformation: "Select Valid Financial Information",
        validateNetWorth: "Select Valid Net Worth",
        validateTaxFilling: "Select Valid Tax Filling",
        validateEmpOccupation: "Enter Valid Occupation",
        validateEmpName: "Enter Valid Employee Name",
        validateEmpLineOne: "Enter Valid Employee Line One"
    },
    accountServices: {
        account_services: 'Account Services',
        bank_accounts: 'BANK ACCOUNTS',
        automatic_investment_plan: 'AUTOMATIC INVESTMENT PLAN',
        systematic_withdrawal_plan: 'SYSTEMATIC WITHDRAWAL PLAN',
        checkbook: 'ORDER CHECKBOOK',
        dividents: 'DIVIDENTS',
        failed_email: 'Failed Email - Member Update'
    },
    dividents: {
        dividents_and_capital_gains_preferences: 'Dividents and Capital Gains Preferences',
        account_name: '-  Account Name',
        current_securities: '-  Current Securities',
        no_do_not_want_to_reinvest: 'I do not Reinvest',
        yes_want_to_reinvest: 'I want to Reinvest',
        future_securites: '-  Future Securities',
        setup_instruction: 'Instructions to Setup and manage Automatic Mutual Fund Purchases',
        reinvest_future_securites: 'Do you want to Reinvest for all future new securities?',
        reinvest_current_securites: 'Do you want to Reinvest Dividends and Capital Gains?',
        lorem_dividents: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        txt_header_dividents: 'To set all future funds purchased in this account to reinvest dividend select "Yes, I want to Reinvest.\n\nTo deposit dividend proceeds into your cash account select "No, I do not Reinvest"',
        amount_remaining: 'Amount Remaining',
        min_amt: 'Min $50',
        dollar_sign: "$",
        lorem_divident_header: "Lorem Ipsum Learn more about Dividends adn Capital Gains",
        lorem_divident_subheader: "Lorem Ipsum Lorem Ipsum Loremm Learn more about Dividends adn Capital Gains",
        dividents_faq: "FAQs",
    },
    //Systematic Investment Plan
    systematicWithdrawal: {
        sysWith_Title: 'Systematic Withdrawal Plan',
        sysWith_current: 'Current Systematic Withdrawal Plans',
        sysWith_current_content: 'There are two parts for an systematic withdrawal within an IRA. The first is the contribution to the account and sencond is the purchase of the mutual fund(s). if you\'re making a change, be sure adjust both parts',
        acc_Name: 'Account Name',
        skip: 'Skip',
    },
    orderCheckBook: {
        order_checkbook: 'Order Checkbook',
        checkbook_requested_on: 'Checkbook requested on',
        number_of_checkleaves: 'Number of Check Leaves',
        verify_your_account: 'Verify your account information below',
        request_submit_checkbook: 'You have successfully Submitted the Checkbook request'
    },
    addBankAccount: {
        addBankAccountHypen: " - ",
        addBankAccountLabel: "Add Bank Account",
        accountType: "Type of Account",
        accountTypeSaving: "Savings",
        accountTypeChecking: "Checking",
        accountFinancialName: "Name of Financial Institution",
        accountOwnerName: "Name of Accouner Owner",
        accountTransitRouting: "Transit Routing Number",
        accountNumber: "Account Number",
        accountSpecimen: "Specimen",
        accountFinancialError: "Enter Valid Financial Number",
        accountOwnerError: "Enter Valid Owner Name",
        accountTransitError: "Enter Valid Transit Routing Number",
        accountValidNumber: "Enter Valid Account Number"
    },
    bankAccounts: {
        bank_account_header: 'Bank Accounts',
        current_bank_accounts: 'Current Bank Accounts',
        lorem_bank_account: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        account_number: 'Account Number',
        transit_routing_number: 'Transit Routing Number',
        date_added: 'Date added',
        add: 'Add'
    },
    addPopularBankAccount: {
        add_bank_account: 'Add Bank Account',
        add_popular_bank_account: 'Add your account by choosing from the popular banks below.',
        popular_account: 'Popular Account',
        instruction_add_account: 'Instruction to Add an Account for Funds Transfer',
    },
    liquidation:{
        isTheReqAmount:"Is the requested amount",
        amountBeforeTaxes:"Amount Before Taxes",
        amountAfterTaxes:"Amount After Taxes",
        federalTax:"Federal Tax",
        stateTax:"State Tax",
        totalTaxToBeWithhold: "Total Taxes to be withhold",
        totalYouWillReceive:"Total you will receive",
        totalWithdrawal: "Total Withdrawal",
        taxAccountingMethod: "Tax Accounting Method",
        taxAccountingMethodContext: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        doNotWithholdTaxes: "Do not withhold Taxes",
        withholdTaxes:"Withhold Taxes",
        onlineMethod:"Online Method",
        offlineMethodContext:"Lorem ipsum dolor sit amet, consectetur adipiscing elitdh Nam imperdiet dictum orcittet",
        offlineMethod: "Offline Method",
        fundSourceContext:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.",
        fundSource:"Fund Source",
        fundWithdrawalHeading:"3 - Fund Withdrawal",
        reviewNConfirmHeading:"4 - Review & Confirm",
        govtSecuritiesFund:"Government Securities Fund",
        tradeType:"Trade Type",
        worthAmount:"Worth Amount",
        sellingAmount:"Selling Amount",
        accountNumber:"Account Number",
        confirmationMsg1:"Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. .",
        confirmationMsg2:"Please wait for 3-5 business days for Settlement of your transaction.",
        targetPage:"TARGET PAGE",
        accountSelectionContent:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.",
        generalAccountHeading:"General Account",
        iraAccountHeading:"IRA Account",
        utmaAccountHeading:"UTMA Account",
        currentValue:"Current Value",
        holding:"Holding",
        automaticInvestmentPlan:"Automatic Investment Plan",
    },
    compareFunds:{
        fundComparison:"Fund Comparison",
        performance : "Performance",       
        performancePrice:"Performance \n& Price",
        sinceInception:"Since \nInception",
        inceptionDate:"Inception \nDate",
        navAsofDate:"NAV \nas of ",
        secYields:"SEC YIELDS",
        secThirtyDay:"30 Day\nas of ",
        secSevenDay:"7 Day\nas of ",
        secWaivers:"(W/o Waivers)",
        expenseRatios:"Expense Ratios",       
        beforeImbursement:"Before\nReimbursement",
        afterImbursement:"After\nReimbursement",
        morningStarRatings:"MorningStar Ratings",
        overAll:"Overall",
        ratingCategory:"Rating\nCategory",
        numberInCategory:"Number in\nCategory",        
    },
    militaryInformationLabel: {
        militaryStatus: 'Military Status',
        militaryBranchService: 'Branch of Service',
        militaryRank: 'Rank',
        militaryDateService: 'Dates of Service',
        militaryDateFrom: 'From',
        militaryDateTo: 'To',
        militaryCommissionSource: 'Commission Source'
    },
    marketingPrivacyLabel: {
        marketingMobileLabel: " -  Mobile",
        marketingContactLabel: "Contact",
        marketingHomeLabel: " -  Home",
        marketingEmailLabel: " -  Email",
        marketingAddressLabel: " -  Address",
        marketingNoneLabel: "None on file",
        marketingNoneMessageLabel: "Please go to basic information page to Add home number",
        marketingProductServiceLabel: "Products & Services",
        marketingExpandLabel: "Expand All",
        marketingInvestmentLabel: "Investments",
        marketingFinancialLabel: "Financial Planning",
        marketingMobilePhoneLabel: "Mobile Phone",
        marketingHomePhoneLabel: "Home Phone",
        marketingMailingLabel: "Mailing Address",
        marketingHeadingLabel: "Settings > Marketing & Privacy",
        marketingPrivacyTitle: "Marketing & Privacy",
        marketingOfferLabel: "How Should We Contact You About Offers?",
        marketingMeetLabel: "To meet your needs better, we 'd like to reach out to you from time to time to let you know about the products and services we have to offer",
        marketingContactUsLabel: "Contact us",
        marketingNoteOne: "We show you gave VCM permission to make marketing calls to you using an automated dialing system or pre recorded voice message. If you want to change you preference.",
        marketingNoteTwo: "What Types of Offers Are You Interested in?",
        marketingNoteThree: "You can tailor the VCM offers you receive and how you like to get them",
        marketingNoteFour: "Please note that your selections do not apply to pre-screened offers of credit. To opt-out of pre-screened offers of credit please visit https://www.optoutprescreen.com or call to free Phone Number. The phone number and website are operated by the major consumer reporting companies",
        
    }
};