# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Submit a new Beta Build to Firebase App Distribution Beta"
  lane :beta do
    # sh "pod install"
    # get_certificates           # invokes cert
    # get_provisioning_profile   # invokes sigh

    # sync_code_signing
    # disable_automatic_code_signing(path: "my_project.xcodeproj")
    build_app(scheme: "MemberServices", export_xcargs: "-allowProvisioningUpdates")
    # enable_automatic_code_signing(path: "my_project.xcodeproj")

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

end
